version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: og_mysql
    environment:
      MYSQL_ROOT_PASSWORD: Krishna@123
      MYSQL_DATABASE: merchandise
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: og_backend
    ports:
      - "5000:5000"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: Krishna@123
      DB_NAME: merchandise
      JWT_SECRET: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEwMDUsIm5hbWUiOiJKb2huIERvZSIsInJvbGUiOjEsImNhbXB1cyI6Ik1haW4gQ2FtcHVzIiwiZGVwdCI6IkNTRSIsImlhdCI6MTc1NTE1OTgyMCwiZXhwIjoxNzU1MTg4NjIwfQ.k6YDFuGU6AAyPRf8IGgz7bqELkTO_oTJvznrwNQao-s
    depends_on:
      - mysql
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: og_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mysql_data: